version: '3'

services:
    db:
        image: postgres
        networks: ['stack']
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
    migration:
        build: .
        command: bash -c "python3 manage.py makemigrations
                && python3 manage.py migrate
                && python3 manage.py seed_data"
        depends_on:
            - db
        networks: ['stack']
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks: ['stack']

networks:
    stack:
        driver: bridge